# -*- coding: utf-8 -*-
"""modelo1_varias_img_seleccion_modelo_geneador_cuadros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yS3F_Ww8EidTZSHL__K0RYf7IG1JXylL
"""

!pip install transformers
!pip install diffusers
!pip install accelerate

from google.colab import drive
drive.mount('/content/drive')

"""**Importaciones**"""

from diffusers import DiffusionPipeline
from PIL import Image
from transformers import pipeline
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
import os
from PIL import Image

"""**Inicialización del modelo de generación de arte.**"""

arte = DiffusionPipeline.from_pretrained("lambdalabs/sd-image-variations-diffusers")

"""**Ruta archivo imagen.**"""

ruta_carpeta = '/content/sample_data/img'

archivos_en_carpeta = os.listdir(ruta_carpeta)

archivos_de_imagen = [archivo for archivo in archivos_en_carpeta if archivo.endswith(('.jpg', '.jpeg', '.png', '.gif'))]

for imagen in archivos_de_imagen:
    ruta_imagen = os.path.join(ruta_carpeta, imagen)
    print('Ruta de la imagen:', ruta_imagen)
    imagen = Image.open(ruta_imagen)

"""**Procesamiento imagen con el modelo seleccionado.**"""

imagen_procesada = arte(imagen)

"""**Impresión imagen**"""

imagen = imagen_procesada.images[0]
display(imagen)